myblog/blog/urls.py
from django.urls import path
from . import views
from .feeds import LastPostsFeed


# we should put app name to specify namespace in main urls
app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    # path('<int:id>', views.post_detail, name='post_detail'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
         views.post_detail, name='post_detail'),

    path('<int:post_id>/share/', views.email_post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    # right way to call class based view LastPostsFeed() not LastPostsFeed
    path('feed/', LastPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap
}
urlpatterns = [
    path('admin/', admin.site.urls),
    # namespace have to be unique accross entire project
    # using----> namespace:urlname-----> blog:post_list
    # blog:post_detail
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

myblog/blog/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
# Create your models here.


class PublishedManger(models.Manager):
    # inherit from models.manager then ovveride the method to make object instead of return
    # Post.objects.all()  ----> Post.published.all() and so on

    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class DraftedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.DRAFT)


# ---------- post model --------------
class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'PUBLISHED'

    title = models.CharField(max_length=250)
    # to ensure that there is no two slugs have the same slug at the same date
    slug = models.SlugField(max_length=250, unique_for_date='published')
    body = models.TextField()
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(
        auto_now_add=True)  # when obj is first created
    updated = models.DateTimeField(auto_now=True)  # when obj is last saved
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT)
    # related_name to allow access related objects to user by user.blog_posts
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')

    objects = models.Manager()  # default manager
    publish_objects = PublishedManger()  # our custom manager
    drafts_objects = DraftedManager()  # our custom manager
    tags = TaggableManager()  # tag custom manager

    class Meta:
        ordering = ['-published']
        # to improve performance
        indexes = [models.Index(fields=['-published'])]

    def __str__(self):
        return self.title

    # removing id from url of post_datil to make seo friendly url
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.published.year,
                                                 self.published.month,
                                                 self.published.day,
                                                 self.slug])


# ---------- comment model --------------
class Comment(models.Model):
    '''
    related name post.comments.all()
    by deafult django made ir post.comment_set.all()
    '''
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created']),]

    def __str__(self) -> str:
        return f'Comment by {self.name} on {self.post}'

myblog/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

myblog/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
# Create your views here.


# def post_search(request):
#     form = SearchForm()
#     query = None
#     results = []
#     if 'query' in request.GET:
#         form = SearchForm(data=request.GET)
#         if form.is_valid():
#             query = form.cleaned_data['query']
#             # fields to search in
#             search_vector = SearchVector(
#                 'title', weight='A', config='spanish') +\
#                 SearchVector('body', weight='B', config='spanish')
#             #  config='spanish' to remove stop words in spanish
#             search_query = SearchQuery(query, config='spanish')
#             '''
#             Filters the search results based on the search query
#             and orders the results by descending relevance rank
#             ----------------------------------------------------
#             Usage with SearchVector: SearchQuery is typically used in
#             combination with SearchVector to perform full-text search in Django
#             '''
#             results = Post.publish_objects.annotate(
#                 search=search_vector,
#                 rank=SearchRank(search_vector, search_query)
#             ).filter(search=search_query).order_by('-rank')

#     return render(request, 'blog/post/search.html', {'form': form,
#                                                      'query': query,
#                                                      'results': results})


# search with trigram
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.publish_objects.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})


def post_list(request, tag_slug=None):

    post_list = Post.publish_objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    # make init from Paginator with max num of posts in page
    paginator = Paginator(post_list, 3)
    # return the paginated page from req by default = 1
    page_number = request.GET.get('page', 1)
    try:
        # pass page_number to paginator.page() which returns the page object
        # with stored posts
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # if page_num in url is passed string not int
        posts = paginator.page(1)
    except EmptyPage:
        # if page_num is out of range in url deliver last page of results
        posts = paginator.page(paginator.num_pages)

    form = CommentForm()
    return render(request, 'blog/post/list.html', {'posts': posts, 'form': form, 'tag': tag})


# another way to make list view by class based views
# but it returns http404 if page is string or out of range
class PostListView(ListView):
    queryset = Post.publish_objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list2.html'


def post_detail(request, year, month, day, post):
    #    post = get_object_or_404(Post,id=id,status = Post.Status.PUBLISHED)
    # removing id from url of post_datil to make seo friendly url
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,
                             slug=post,
                             published__year=year,
                             published__month=month,
                             published__day=day)
    # comments from related_name = comments in models.py
    comments = post.comments.filter(active=True)
    form = CommentForm()

    # list of similar posts
    post_tags_ids = post.tags.values_list(
        'id', flat=True)  # flat to return list not tuples
    published_posts = Post.publish_objects.all()
    similar_posts = published_posts.filter(
        tags__in=post_tags_ids).exclude(id=post.id)  # exclude the post itself
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-published')[:4]
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'form': form,
                                                     'similar_posts': similar_posts})


def email_post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id,
                             status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            '''After the form data has been validated, you can access the cleaned form 
            input data through the form.cleaned_data attribute. 
            This attribute provides a dictionary where the keys are the field names defined in the form,
            and the values are the cleaned and validated values entered by the user
            '''
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends your read"\
                f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n"\
                f"{cd['name']} \'s comments: {cd['comments']}"
            send_mail(subject, message,
                      'abdelrhmanmamdouh776@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'blog/post/comment.html', {'post': post,
                                                      'form': form,
                                                      'comment': comment})

myblog/blog/templates/blog/post/comment.html
{% extends 'blog/base.html'%}
{% block title %} Add a comment {% endblock%}
{% block content %}
{% if comment %}
<p>Your comment has been added succeffully.</p>
<p><a href="{{post.get_absolute_url}}">return to post</a></p>
{% else %}
{% include "blog/post/includes/comment_form.html"%}
{% endif %}
{% endblock %}

myblog/blog/templates/blog/post/detail.html
{% extends 'blog/base.html'%}
{% load blog_tags %}
{% block title %} {{post.title}} {% endblock %}
{%block content %} 
{% comment %} dispalying post details {% endcomment %}
<h1>{{ post.title }}</h1>
<p class="date">published {{post.published}} by {{post.author}}</p>
{% comment %} {{post.body|linebreaks}} {% endcomment %}
{{post.body|markdown}}

<p>
  <a href='{% url "blog:post_share" post.id %}'> Share this post </a>
</p>
<p>
  <a href='{% url "blog:post_list" %}'> Return to posts</a>
</p>
<h2>Similar Posts </h2>
<!-- displaying similar posts -->
{% for post in similar_posts%}
<p>
  <a href='{{ post.get_absolute_url }}'>{{ post.title }}</a>
</p>
{% empty %}
<p>There are no any similiar posts yet!</p>
{% endfor %}
{% comment %} total number of comments {% endcomment %} 
{% with comments.count as total_comments %} 
{{total_comments}} comment{{total_comments|pluralize}} 
{%endwith %} 
{% comment %} display all active comments {% endcomment %} 
{% for comment in comments %}
<div class="comment">
  <p class="info">
    Comment {{forloop.counter}} by {{comment.name}} {{comment.created}}
  </p>
  {{comment.body|linebreaks }}
</div>
{% empty %}
<p>there is no comments</p>
{% endfor %} 
{% include "blog/post/includes/comment_form.html" %} 
{% endblock %}

myblog/blog/templates/blog/post/latest.html
<ul>
    {% for post in latest_posts %}
    <li>
    <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a> 
    </li>
    {% endfor %}
</ul>

myblog/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}
<h1>MyBlog</h1>
{% endblock%} {% block content%} 
{% if tag %}
  <h2> posts tagged with "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts %}
<h2>
  <!-- blog:post_detail === from namespace  -->
  {% comment %}
   <a href="{% url 'blog:post_detail' post.id %}"> {{post.title}} </a> 
  {% endcomment %}
  <a href="{{ post.get_absolute_url}}"> {{post.title}} </a>
</h2>
{% comment %} <p class="tags">Tags: {{ post.tags.all|join:", " }} </p> {% endcomment %}
<p class="tags">Tags: 
{% for tag in post.tags.all %}
  <a  href="{% url 'blog:post_list_by_tag' tag.slug %}">
  {{ tag.name }}
  </a>
  {% if not forloop.last %}, {% endif %}
{% endfor %}
 </p>
<p class="date">published {{post.published}} by {{post.author}}</p>
{{post.body|markdown|truncatewords_html:30}} 
{% comment %} {{post.body|truncatewords:30|linebreaks}}  {% endcomment %}

{% endfor%} 
<!-- to render page with its post page=posts -->
{% include "blog/post/pagination.html" with page=posts%}
{% comment %} {% include "blog/post/includes/comment_form.html" %}  {% endcomment %}
{% endblock %}

myblog/blog/templates/blog/post/list2.html
{% extends 'blog/base.html' %} {% block title %}
<h1>MyBlog</h1>
{% endblock%} {% block content%} {% for post in posts %}
<h2>
  <!-- blog:post_detail === from namespace  -->
  {% comment %}
   <a href="{% url 'blog:post_detail' post.id %}"> {{post.title}} </a> 
  {% endcomment %}
  <a href="{{ post.get_absolute_url}}"> {{post.title}} </a>
</h2>
<p class="date">published {{post.published}} by {{post.author}}</p>
{{post.body|truncatewords:30|linebreaks}} {% endfor%} 
<!-- to render page with its post page=posts -->
{% include "blog/post/pagination.html" with page=page_obj%}
{% endblock %}

myblog/blog/templates/blog/post/pagination.html
<div class="pagination">
    <span class="step_links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{page.number}} of {{ page.paginator.num_pages }}
        </span>
            {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
            {% endif %}
        
    </span>
</div>

myblog/blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %} {% block content  %}

{% if query %}
<h1> Posts containing  {{query}}</h1>
{% with results.count as total_results%}
 Found {{total_results}} results
{% endwith %}
{% for post in results%}
<h4>
    <a href="{{post.get_absolute_url}}">
    {{post.title}}
    </a>
</h4>
{{post.body|markdown|truncatewords_html:10}}
{% empty %}
<p> There are no results for our query</p>
{% endfor %}
{% comment %} <a href="{% url 'blog:post_search' %}">
    Search Again
<a>  {% endcomment %}
 <a href="{% url 'blog:post_search' %}">
    <button>
        Search Again
    </button>
<a> 
{% else %}
<form method="GET">
{{form.as_p}}
<input type="submit" value="search" />
</form>
{% endif %}
{% endblock %}

myblog/blog/templates/blog/post/share.html
{% extends 'blog/base.html'%}
{% block title %} share a post {% endblock %}
{% block content %} 
{% if sent %}
<h1>Email Sent Successfully</h1>
<br />
<p>"{{post.title}}" was successfully sent to {{form.cleaned_data.to}}</p>
{% else %}
<h1>Share "{{post.title}}" by e-mail</h1>
<form action="" method="post" >
  {{ form.as_p }} 
  {% csrf_token %}
  <input type="submit" value="Send E-mail" />
</form>
{% endif %}
{%endblock%}